version: '2.3'
services:
  zoomdata-edc-postgresql:
    hostname: zoomdata-edc-postgresql
    image: ${EDC_REPO}zoomdata-edc-postgresql:${EDC_TAG}
    environment:
      DISCOVERY_REGISTRY_HOST: zoomdata-consul
    ports:
      - 8105:8105
    volumes:
      - ./${CONFIG_SET}:/etc/zoomdata
      - ./logs:/opt/zoomdata/logs
    stop_grace_period: 15s
    depends_on:
      - zoomdata-consul
