version: '2.3'
services:
  zoomdata-edc-rts:
    hostname: zoomdata-edc-rts
    image: ${EDC_REPO}zoomdata-edc-rts:${EDC_TAG:-latest}
    environment:
      DISCOVERY_REGISTRY_HOST: zoomdata-consul
    ports:
      - 8108:8108
    volumes:
      - ./${CONFIG_SET}:/etc/zoomdata
      - ./logs:/opt/zoomdata/logs
    stop_grace_period: 15s
    depends_on:
      - zoomdata-consul
