version: '2.3'
services:
  zoomdata-edc-apache-solr:
    hostname: zoomdata-edc-apache-solr
    image: ${EDC_REPO}zoomdata-edc-apache-solr:${EDC_TAG:-latest}
    environment:
      DISCOVERY_REGISTRY_HOST: zoomdata-consul
      LOG_CONSOLE_LEVEL: ${LOG_CONSOLE_LEVEL}
      LOG_FILE_LEVEL: ${LOG_FILE_LEVEL}
    ports:
      - 8115:8115
    volumes:
      - ./${CONFIG_SET}:/etc/zoomdata
      - ./logs:/opt/zoomdata/logs
    stop_grace_period: 15s
    depends_on:
      - zoomdata-consul
